image: centos:centos8.2.2004

build:
  script:
    - yum -y install rpm-build
    - rpmbuild --target noarch -bb deployment.spec
    - cd ../../../../../../

  artifacts:
    paths:
      - ../../../../root/rpmbuild/RPMS