image: centos:centos8.2.2004

build:
  script:
    - yum -y install rpm-build
    - mkdir -p rpmbuild/{BUILD,BUILDROOT,RPMS,SRPMS}
    - mkdir -p rpmbuild/RPMS/noarch
    - cd rpmbuild/SPECS
    - rpmbuild --target noarch -bb deployment.spec
    - cd ../RPMS/noarch
    - ls

  artifacts:
    paths:
      - rpmbuild/RPMS